### ISSUE TITLE
Conflicts with Worldedit

### ISSUE THREAD

**Issue by SalmonSnakeD** [percivalalb/MapMakingTools#4]
This mods commands conflict withworld edit //set //undo //redo ect.. can you do commands with 3 slashes or 1? or change it like this //redo- //undo-

**Comment by percivalalb** [comment]
I've added the ability to configure the format of the quick build commands. Located in the common config `config/mapmakingtools-common.tml`

For example:
```
[Commands]

	[Commands."Quick Build"]
		format = "qb-<cmd>"

```
would mean the commands would be `/qb-set`, `/qb-redo` etc. Use `<cmd>` to represent the name of the command

This should solve your problem!
